const SUPABASE_URL = 'https://caiaqqsmvlztfnyyglss.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhaWFxcXNtdmx6dGZueXlnbHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc4MzQ3MzIsImV4cCI6MjA5MzQxMDczMn0.b4O-qQwWaU75to0XwFBfe8DegWXfMScuTGTehfYjX0c';

window.sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
